server:
  port: 8040

spring:
  application:
    name: springcloud-config-bus-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wwg2008123/spring-cloud-config
          search-paths: git-config
          username: wwg2008123
          password: wwg888888
          label: master
    bus:
      trace:
        enabled: true

  rabbitmq:
    host: 192.168.65.130
    port: 5672
    username: wwg  #rabbitmq 默认账号和密码是guest
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

management:
  endpoint:
    bus-refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: bus-refresh
