spring:
  application:
    name: gateway-zuul
server:
  port: 8888

zuul:
  routes:
    first:
      path: /it/**
      url: https://www.baidu.com/
    second:
      path: /producer/**
      serviceId: service-demo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
