spring:
  application:
    name: gateway
server:
  port: 9999

zuul:
  routes:
    first:
      path: /baidu/**
      url: https://www.baidu.com/
    one:
      path: /user/**
      serviceId: service-demo
    two:
      path: /catch/**
      serviceId: service-demo2
    three:
      path: /other/**
      serviceId: service-demo3
  #prefix: api #给每个服务的API接口加前缀,如http://localhost:5000/v1/it/hi?name=cralor

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
