server:
  port: 8033  #注册中心8001
spring:
  application:
    name: spring-config-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wwg2008123/projectconfig.git
          username: wwg2008123
          password: wwg888888s
          search-paths: cfg*
eureka:
  client:
    service-url:
      defaultZone: http://192.168.65.130:8002/eureka/,http://192.168.65.130:8003/eureka/
